@startuml BackOfficeContainerDiagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(ventas, "Ventas y Marketing", "Gestiona contratos y tarifas")
Person(atencioncliente, "Atención al Cliente", "Gestiona clientes y atiende consultas")
Person(f, "Finanzas", "Genera y envía facturas")

System_Boundary(c1, "Back Office System") {
    Container(gcontratos, "Sistema de gestion de contratos", , "Gestiona la información de clientes y contratos")
    Container(gclientes, "Sistema de gestion de clientes", ,"Gestiona la información de clientes")
    Container(factura, "Sistema de Facturación", , "Genera y envía facturas")
}

System_Ext(bd, "Base de Datos de Clientes", "Almacena información de contratos, líneas y facturacion")

Rel(ventas, gcontratos, "Usa", "???")
Rel(atencioncliente, gclientes, "Usa", "???") 
Rel(f, factura, "Usa", "???")

Rel(gcontratos, bd, "Añade datos", "???")
Rel(bd, gcontratos, "Recoge datos", "???")
Rel(gclientes, bd, "Añade datos", "???")
Rel(bd, gclientes, "Recoge datos", "???")
Rel(factura, bd, "Añade datos", "???")
Rel(bd, factura, "Recoge datos", "???")

@enduml
