@startuml ConceptualDataModel
title Modelo Conceptual de Datos
!theme materia
left to right direction

entity "Usuario" as usuario {
  + ID de usuario (PK)
  + Nombre de usuario
  + Nombre
  + Apellido
  + Email
  + Rol
}

entity "Rol" as rol {
  + Valor (PK)
}

entity "Contrato" as contrato {
  + ID de contrato (PK)
  + ID de usuario (FK)
  + Duración del contrato
  + Fecha de inicio
  + Fecha de fin
  + Datos compartidos?
}

entity "Línea" as linea {
  + ID de línea (PK)
  + Nombre de línea
  + Descripción
  + Precio por minuto
  + Precio por Megabyte
  + Duración mínima
  + Minutos gratis
  + Megabytes gratis

}

entity "Línea de cliente" as lineaCliente {
  + ID de línea de cliente (PK)
  + ID de contrato (FK)
  + ID de línea (FK)
  + Número de teléfono
  + Roaming?
  + Precio por minuto
  + Precio por Megabyte
  + Minutos gratis
  + Megabytes gratis
}

entity "Factura" as factura {
  + ID de factura (PK)
}

entity "Llamada" as llamada {
  + ID de llamada (PK)
  + Número de teléfono de origen (FK)
  + Número de teléfono de destino (FK)
  + Fecha
  + Duración
}

entity "Consumo de datos" as consumoDatos {
  + ID de consumo de datos (PK)
  + Número de teléfono (FK)
  + Megabytes
  + Fecha
}

entity "Reclamación" as reclamacion {
  + ID de reclamación (PK)
  + ID de línea de cliente (FK)
  + Asunto
  + Estado (FK)
  + Fecha
}

entity "Mensaje de reclamación" as msgReclamacion {
  + ID de mensaje (PK)
  + ID de reclamación (FK)
  + ID de mensaje padre (FK)
  + Contenido 
  + Fecha y hora

}

entity "Estado de reclamación" as estadoReclamacion {
  + Valor (PK)
}

entity "Bloqueo de número" as bloqueoNumero {
  + ID de bloqueo (PK)
  + Número de teléfono del bloqueador (FK)
  + Número de teléfono del bloqueado  (FK)
}

usuario "1" -- "1..*" rol
usuario "1" -- "1..*" contrato

contrato "1" -- "1..*" lineaCliente
contrato "1" -- "*" factura


linea "1" -- "*" lineaCliente

lineaCliente "1" -- "*" llamada
lineaCliente "1" -- "*" consumoDatos
lineaCliente "1" -- "*" bloqueoNumero
lineaCliente "1" -- "*" reclamacion

reclamacion "1" -- "*" msgReclamacion : tiene
reclamacion "1" -- "1" estadoReclamacion : tiene
msgReclamacion "1" -- "1" msgReclamacion : mensaje padre


@enduml
