@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Diagrama de Contexto

Person(ventas, "Personal de Ventas y Marketing", "Gestiona las lineas y tarifas")
Person(atencioncliente, "Personal de Atención al Cliente", "Gestiona clientes, contratos y atiende consultas y reclamaciones")
Person(f, "Personal de Finanzas", "Genera y envía facturas")
Person(admin, "Personal de Administración", "Gestiona el personal y la configuracion del sistema")
Person(cliente, "Cliente", "Persona que utiliza la plataforma para gestionar y contratar servicios.")

System(t, "TelefonUCA", "Operadora virtual de telecomunicaciones")

System_Ext(omr, "Operador Móvil de Red (OMR)", "Ofrece una API HTTP para la gestión de líneas móviles y consulta de consumos.")
SystemDb_Ext(bd, "Base de Datos", "Almacena contratos, consumos, facturas y configuraciones.", "MySQL")

Rel(cliente, t, "Utiliza")
Rel(t, bd, "Consulta y actualiza")
Rel(t, omr, "Se comunica via API HTTP")

Rel(ventas, t, "Utiliza")
Rel(atencioncliente, t, "Utiliza")
Rel(f, t, "Utiliza")
Rel(admin, t, "Utiliza")

@enduml