@startuml PventasComponentDiagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


Person(ventas, "Personal de Ventas y Marketing", "Gestiona las lineas y tarifas")

System_Boundary(pv, "Portal de ventas", "Gestiona la información de clientes y contratos") {

        Component( pi, "Página de inicio", , "Página de inicio del portal de ventas")
        Component( pu, "Página de usuarios", , "Muestra una lista de usuarios")
        Component( pc, "Página de contratos", , "Muestra una lista de contratos")

}

System_Ext(bd, "Base de Datos","Almacena información de contratos, líneas, clientes y facturacion", "MySQL")


Rel(ventas,pi,"Accede")
Rel(ventas,pu,"Accede")
Rel(ventas,pc,"Accede")

Rel(pi, bd, "Consulta y actualiza")
Rel(pu, bd, "Consulta y actualiza")
Rel(pc, bd, "Consulta y actualiza")


@enduml
