@startuml FrontOffice
!theme materia
left to right direction

actor Cliente as client

rectangle "Front Office System" {
    client -- (Registro de Usuario)
    client -- (Activación de usuario)
    client -- (Adquirir un nuevo contrato)
    client -- (Adquirir una nueva línea de cliente) 
    client -- (Gestionar mis contratos)
    client -- (Gestionar mis líneas de cliente)
    client -- (Consultar volumen mensual de llamadas)
    client -- (Consultar desglose de llamadas)
    client -- (Consultar desglose de consumo de datos)
    client -- (Consultar volumen mensual de datos)
    client -- (Consultar mis facturas)
    client -- (Descargar factura en PDF)
    client -- (Recibir factura por email)
    client -- (Realizar reclamación)
    client -- (Consultar mis reclamaciones)
}




@enduml
