@startuml FrontOffice
!theme materia
left to right direction

actor "Ventas y marketing" as salesMarketing <<Empleado>>
actor "Atención al cliente" as customerService <<Empleado>>
actor "Finanzas" as finance <<Empleado>>

rectangle "Back Office System" {
    salesMarketing -- (Gestionar líneas a ofertar)
    customerService -- (Gestionar contratos)
    customerService -- (Gestionar líneas de cliente)
    customerService -- (Responder reclamación)
    customerService -- (Editar reclamación)
    finance -- (Generar facturas)
    finance -- (Enviar facturas)

}
@enduml
