name: Generate PlantUML Diagrams
on:
  push:
    branches: [ main ]
    paths:
      - 'docs/diagrams/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/diagrams/**'
permissions:
  contents: write
  packages: write

jobs:
 generate_diagrams:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout Repo
     uses: actions/checkout@v2

   - name: Generate Diagrams
     uses: grassedge/generate-plantuml-action@v1.5
     with:
       path: docs/diagrams
       message: "Render PlantUML files"
     env:
       GITHUB_TOKEN: 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

   - name: Move Images to img directory
     run: mv docs/diagrams/*.svg docs/diagrams/img/

   - name: Delete Images from source directory
     run: find docs/diagrams -name '*.svg' -delete

   - name: Commit and Push
     run: |
       git config --global user.name 'github-actions'
       git config --global user.email 'github-actions@github.com'
       git add docs/diagrams/img/*
       git commit -m "Update PlantUML diagrams" || exit 0
       git push
